LOCATION=asia-northeast1
REPO_NAME=image-repo
APP_NAME=bg-remover

BACKEND_IMAGE=$APP_NAME-service
APP_IMAGE=$APP_NAME-app
MODEL_NAME=$APP_NAME-model
ENDPOINT_NAME=$APP_NAME-ep
SERVICE_NAME=$APP_NAME-app
SERVICE_ACCOUNT_NAME=$APP_NAME-frontend
